enable_database: true
enable_kafka_producer: true
kafka_config:
  brokers:
    - "kafka:9094"
kafka_topic: "post_products"

database:
  db_datasource: "postgres://postgres:postgres@postgres:5432/postgres"
api:
  service-2:
    base_url: "http://service-2:8080"
