version: '3'

# volumes:
#   prometheus-data:
#     driver: local
#   grafana-data:
#     driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    # volumes:
    #   - grafana-data:/var/lib/grafana
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      # - ./tempo-data:/var/tempo
    ports:
      # - "14268"  # jaeger ingest
      - "3200"   # tempo
      # - "4317"  # otlp grpc
      # - "4318"  # otlp http
      # - "9411"   # zipkin
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    command:
      - "--config=/etc/otel-collector-config.yaml"
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      # - "1888:1888"   # pprof extension
      # - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      # - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      # - "4318:4318"   # OTLP http receiver
      # - "55679:55679" # zpages extension
